### ISSUE TITLE
[BUG] RAM does not get cleared upon closing a graphical application

### ISSUE THREAD

**Issue by Thorgrym** [ThePorgs/Exegol-images#311] opened 2024-02-22 13:22 UTC
### Describe the bug

Bug on MacOS with Orbstack and Windows with Docker Desktop

When I open a graphical application like Firefox or Burp the RAM that is used by Exegol increase but never reduce when I close the application,  even if I stop the container. It is cleared only if I reboot Orbstack/Docker Desktop

Exemple :

RAM used with a fresh container :
<img width="711" alt="image" src="https://github.com/ThePorgs/Exegol-images/assets/160862733/b2103247-f6e9-4e35-ae7e-2a1a4c86083b">

Then Open Firefox :
<img width="711" alt="image" src="https://github.com/ThePorgs/Exegol-images/assets/160862733/7be8fda9-0d2c-4902-9645-ed48592a04b9">

Close Firefox :
<img width="711" alt="image" src="https://github.com/ThePorgs/Exegol-images/assets/160862733/0edf2221-dc35-4aca-9d56-a09191c79217">

Finally close the container :
<img width="696" alt="image" src="https://github.com/ThePorgs/Exegol-images/assets/160862733/be9135d4-56e6-477a-b00c-ba573a4eb00a">

Sometimes when I close exegol after a session of 2/3h it use like 10Gb of RAM so it stacks up pretty quickly 

### Steps To Reproduce

Open firefox or Burp in exegol, look at your RAM in your task manager, then close the application and stop the container and look again.

### Exegol Wrapper Version

```Text
[*] Exegol is currently in version v4.3.1
```

### Exegol container information

```Text
It was a fresh new container of the full version of exegol, just created by "exegol start work"
```

### Anything else?

It's my first ever Issue on github so I'm sorry if I made something wrong. I also didn't know if I had to post this in the Exegol WRAPPER project or here.

If any more information is needed just ask and I will do my best.

**Comment by ShutdownRepo** [comment] 2024-04-05 17:14
I honestly have no idea what could cause this. From what I can read from your post, it happens on both OrbStack (macOS) and Docker Desktop (windows). It also happens on both Firefox and Burp. 
I don't think the issue is in Exegol it self neither since we don't do anything particular with the apps or GUI.
@Dramelac @QU35T-code any idea on your end?

**Comment by Dramelac** [comment] 2024-04-05 17:30
Seems like an error on orbstack side. Once the container is stopped there is no more resources consumption. 
We should open an issue on orbstack repo with a PoC (without exegol if possible).

**Comment by ShutdownRepo** [comment] 2024-04-05 18:25
> Seems like an error on orbstack side. Once the container is stopped there is no more resources consumption. We should open an issue on orbstack repo with a PoC (without exegol if possible).

issue on windows docker desktop as well apparently

**Comment by cHJlaXpoZXI** [comment] 2024-08-19 09:59
FYI, Orbstack has release a beta version with dynamic memory.

The complete changelog : https://docs.orbstack.dev/release-notes#v1-7-0-rc1

Maybe try this version to see if the issue is still here ?

**Comment by ShutdownRepo** [comment] 2024-09-04 13:42
Closing this, hoping the new version effectively fixed it
Please feel free to re-open if needed

**Closed by ShutdownRepo** 2024-09-04 13:42 UTC
Labels: bug, help wanted
